NameError: name '_PRICE_RE' is not defined
NameError                                 Traceback (most recent call last)
/tmp/ipykernel_113/1215835711.py in <module>
      1 if __name__ == "__main__":
----> 2     excecute_process()

/tmp/ipykernel_113/511133302.py in excecute_process()
     35 
     36         # Parsear (horizontal)
---> 37         df = pfh.read_file(str(local_pdf_path))
     38 
     39         # Observa columnas

~/competitor_data/purina_file_horizontal.py in read_file(pdf)
    258         ~df.apply(
    259             lambda row: _PRICE_RE.search(" ".join(row.astype(str)).upper()) is not None,
--> 260             axis=1,
    261         )
    262     ].reset_index(drop=True)

~/.local/lib/python3.7/site-packages/pandas/core/frame.py in apply(self, func, axis, raw, result_type, args, **kwargs)
   8738             kwargs=kwargs,
   8739         )
-> 8740         return op.apply()
   8741 
   8742     def applymap(

~/.local/lib/python3.7/site-packages/pandas/core/apply.py in apply(self)
    686             return self.apply_raw()
    687 
--> 688         return self.apply_standard()
    689 
    690     def agg(self):

~/.local/lib/python3.7/site-packages/pandas/core/apply.py in apply_standard(self)
    810 
    811     def apply_standard(self):
--> 812         results, res_index = self.apply_series_generator()
    813 
    814         # wrap results

~/.local/lib/python3.7/site-packages/pandas/core/apply.py in apply_series_generator(self)
    826             for i, v in enumerate(series_gen):
    827                 # ignore SettingWithCopy here in case the user mutates
--> 828                 results[i] = self.f(v)
    829                 if isinstance(results[i], ABCSeries):
    830                     # If we have a view on v, we need to make a copy because

~/competitor_data/purina_file_horizontal.py in <lambda>(row)
    257     df = df[
    258         ~df.apply(
--> 259             lambda row: _PRICE_RE.search(" ".join(row.astype(str)).upper()) is not None,
    260             axis=1,
    261         )

NameError: name '_PRICE_RE' is not defined
