[1/1] Procesando: 2025.03.03 Statesville.pdf
Got stderr: May 07, 2025 3:25:04 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'LiberationSans' for 'ArialMT'

KeyError: 'product_desc'
KeyError                                  Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3360             try:
-> 3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:

~/.local/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

~/.local/lib/python3.7/site-packages/pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'product_desc'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_117/1215835711.py in <module>
      1 if __name__ == "__main__":
----> 2     excecute_process()

/tmp/ipykernel_117/511133302.py in excecute_process()
     35 
     36         # Parsear (horizontal)
---> 37         df = pfh.read_file(str(local_pdf_path))
     38 
     39         # Observa columnas

~/competitor_data/purina_file_horizontal.py in read_file(pdf)
    343     df.dropna(how="all", inplace=True)
    344     
--> 345     df = add_species_column(df)
    346 
    347     # Metadatos

~/competitor_data/purina_file_horizontal.py in add_species_column(df)
    305         # 1) ¿Fila-categoría?
    306         is_numeric_row = any(pd.notna(row[c]) for c in price_cols)
--> 307         is_text_only   = pd.notna(row["product_desc"]) and not is_numeric_row
    308 
    309         if is_text_only:

~/.local/lib/python3.7/site-packages/pandas/core/series.py in __getitem__(self, key)
    940 
    941         elif key_is_scalar:
--> 942             return self._get_value(key)
    943 
    944         if is_hashable(key):

~/.local/lib/python3.7/site-packages/pandas/core/series.py in _get_value(self, label, takeable)
   1049 
   1050         # Similar to Index.get_value, but we do not fall back to positional
-> 1051         loc = self.index.get_loc(label)
   1052         return self.index._get_values_for_loc(self, loc, label)
   1053 

~/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   3361                 return self._engine.get_loc(casted_key)
   3362             except KeyError as err:
-> 3363                 raise KeyError(key) from err
   3364 
   3365         if is_scalar(key) and isna(key) and not self.hasnans:

KeyError: 'product_desc'
